language: php

env: 
  global:
    - MWEXTNAME=StructuredNavigation
    - DBTYPE=mysql
    - DBUSER=root
    - BRANCH=REL1_32

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        - name: "PHP 7.1, MediaWiki 1.32"
          php: 7.1

        - name: "PHP 7.2, MediaWiki 1.32"
          php: 7.2

        - name: "PHP 7.3, MediaWiki 1.32"
          php: 7.3

        - name: "PHP nightly build, MediaWiki 1.32"
          php: nightly

    allow_failures:
        - php: 7.3
        - php: nightly

before_install:
  - composer self-update

  # clone MediaWiki, version 1.32
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/core.git --branch $BRANCH mediawiki

  # get into our MediaWiki instance directory
  - cd mediawiki

  # install composer dependencies
  - composer install

  # do actual install
  - php maintenance/install.php
    --pass travis
    --dbtype "$DBTYPE"
    --dbuser "$DBUSER"
    --dbname travisciwiki
    --dbpass ""
    --scriptpath "/w" \
    -- lang "en"

  # include development environment settings
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php

install:
  # get into the /extensions folder of our MediaWiki instance
  - cd extensions

  # actually install our extension
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $MWEXTNAME
  - cd $MWEXTNAME
  - git checkout -qf $TRAVIS_COMMIT
  - composer install

  # go back to the mediawiki directory
  - cd ../../
  - echo "\n\nwfLoadExtension( '$MWEXTNAME' );\n" >> ./LocalSettings.php


script:
  # Go back to our extension's directory because we don't want
  # to run these checks against the entirety of MediaWiki core
  - cd extensions/$MWEXTNAME

  - composer test
  - composer metrics

notifications:
  email:
    recipients:
      - samanthanguyen1116@gmail.com
    on_success: change
    on_failure: always